# Intro
It's about programming in Julia, but this time we are looking for intermediate concepts in Julia Programming. 

In [7]:
# Preparations
using Pkg
Pkg.add("BenchmarkTools")
using BenchmarkTools

    Updating registry at `C:\Users\victo\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed BenchmarkTools ─ v1.1.1
    Updating `C:\Users\victo\.julia\environments\v1.6\Project.toml`
  [6e4b80f9] + BenchmarkTools v1.1.1
    Updating `C:\Users\victo\.julia\environments\v1.6\Manifest.toml`
  [6e4b80f9] + BenchmarkTools v1.1.1
  [37e2e46d] + LinearAlgebra
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
Precompiling project...
  ✓ BenchmarkTools
  1 dependency successfully precompiled in 2 seconds (15 already precompiled)


### **Arrays, Speed, Operations and Arithmetic**
* iterable as column vectors
* Elementwise operations and assignments
* Linear indexing of array and fast memory indexing via `eachindex`
* Array in Julia is Column Major. 
  * Boardcase assignment via slicer. 


In [2]:
# iterable type and arrays
a = 1:5
println(typeof(a))
b = [1, 2, 3, 4, 5]
println(a + b)
# iterable are like column vectors. 

UnitRange{Int64}


5-element Vector{Int64}:
  2
  4
  6
  8
 10

In [11]:
# Elementwise opeartions with elementwise assignment 
A = rand(3, 3)
B = rand(3, 3)
C = rand(3, 3)
D = zeros(3, 3)
D .= A.*B.+C


3×3 Matrix{Float64}:
 0.840454  1.36908   1.08135
 0.817489  0.833859  1.55651
 0.558566  0.541098  0.78451

In [16]:
# Memory optimized iterations
A = rand(3, 3)
s = 0
for II in eachindex(A)
    print(string(II)*" ")
end
# Linear indexing for multi-dimensional array, becareful about that part. 

1 2 3 4 5 6 7 8 9 

In [24]:
# Linear indexing reveals that Julia is COLUMN MAJOR
A = rand(3, 3)
A[8] = -Inf
display(A)
# Boardcase assignmend via linear indexing. 
A[1:2] .= +NaN
display(A)

3×3 Matrix{Float64}:
 0.958409  0.82296     0.035831
 0.911869  0.737836  -Inf
 0.026668  0.911474    0.405428

3×3 Matrix{Float64}:
 NaN         0.82296     0.035831
 NaN         0.737836  -Inf
   0.026668  0.911474    0.405428